name: Build Flatpak
on:
  workflow_call:
    inputs:
      ref:
        description: Branch, tag or SHA to checkout.
        type: string
        required: true
      arch:
        description: Architecture of the build.
        type: string
        default: x86_64
      flatpak-branch:
        description: Flatpak branch
        type: string
        default: master
      publish-mode:
        description: Change workflow behavior and override following options to upload ready to export builddir
        type: boolean
        default: false
      upload-bundle:
        description: Generate and upload Flatpak bundle as artifact
        type: boolean
        default: false
      save-cache:
        description: Enable saving cache if the internal cache-key is not hit
        type: boolean
        default: false
env:
  CACHE_PATH: ${{ github.workspace }}/.flatpak-builder
  CACHE_KEY: flatpak-${{ inputs.arch }}-
  FLATPAK_BUILD_DIR: builddir-${{ inputs.arch }}
  FLATPAK_BUILD_SHARE_PATH: builddir-${{ inputs.arch }}/files/share
jobs:
  build:
    runs-on: ${{ inputs.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    defaults:
      run:
        shell: bash
    steps:
      - name: Check artifact type
        run: |
          : Check workflow inputs
          if ! [[ "${{ inputs.arch }}" =~ x86_64|aarch64 ]]; then
            echo "::error::Given arch is incorrect"
            exit 2
          fi

          if ! [[ "${{ inputs.flatpak-branch }}" =~ master|stable|beta ]]; then
            echo "::error::Given flatpak-branch is incorrect"
            exit 2
          fi

          if [[ "${{ inputs.publish-mode }}" == "true" && "${{ inputs.flatpak-branch }}" == "master" ]]; then
            echo "::error::\"master\" as flatpak-branch is incorrect in publish mode"
            exit 2
          fi

      - uses: actions/checkout@v4
        id: checkout
        with:
          submodules: recursive
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - uses: actions/cache/restore@v4
        id: restore-cache
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}

      - name: Validate Flatpak manifest
        uses: ./.github/actions/flatpak-builder-lint
        with:
          artifact: manifest
          path: build-aux/com.obsproject.Studio.json

      - name: Build
        run: |
          : Build
          flatpak-builder \
          ${{ inputs.publish-mode && '' || '--repo=repo ' }}\
          --default-branch=${{ inputs.flatpak-branch }} \
          --arch=${{ inputs.arch }} \
          --ccache \
          --mirror-screenshots-url=https://dl.flathub.org/media \
          ${{ env.FLATPAK_BUILD_DIR }} \
          ${{ github.workspace }}/build-aux/com.obsproject.Studio.json

      - name: Validate AppStream
        uses: ./.github/actions/flatpak-builder-lint
        with:
          artifact: appstream
          path: ${{ env.FLATPAK_BUILD_SHARE_PATH }}/metainfo/com.obsproject.Studio.metainfo.xml

      - name: Verify Icon and Metadata in app-info
        working-directory: ${{ env.FLATPAK_BUILD_SHARE_PATH }}
        run: |
          : Verify Icon and Metadata in app-info
          test -f app-info/icons/flatpak/128x128/com.obsproject.Studio.png || { echo "::error::Missing 128x128 icon in app-info"; exit 1; }
          test -f app-info/xmls/com.obsproject.Studio.xml.gz || { echo "::error::Missing com.obsproject.Studio.xml.gz in app-info"; exit 1; }

      - name: Validate build directory
        uses: ./.github/actions/flatpak-builder-lint
        with:
          artifact: builddir
          path: ${{ env.FLATPAK_BUILD_DIR }}

      - name: Commit screenshots
        if: !inputs.publish-mode
        run: |
          : Commit screenshots
          ostree commit \
          --repo=repo \
          --canonical-permissions \
          --branch=screenshots/${{ inputs.arch }} \
          ${{ env.FLATPAK_BUILD_SHARE_PATH }}/app-info/media

      - name: Validate repository
        if: !inputs.publish-mode
        uses: ./.github/actions/flatpak-builder-lint
        with:
          artifact: repo
          path: repo

      - name: Generate bundle
        id: bundle
        if: !inputs.publish-mode && inputs.upload-bundle
        env:
          COMMIT: ${{ steps.checkout.outputs.commit }}
        run: |
          : Generate bundle

          name=obs-studio-flatpak-${{ inputs.arch }}-${COMMIT:0:9}
          file_name="${name}.flatpak"

          echo "name=${name}" >> $GITHUB_OUTPUT
          echo "file-name=${file_name}"  >> $GITHUB_OUTPUT

          flatpak build-bundle \
          --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
          --arch=${{ inputs.arch }} \
          repo ${file_name} com.obsproject.Studio

      - name: Upload bundle
        if: steps.bundle.conclusion == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.bundle.outputs.name }}
          path: ${{ github.workspace }}/${{ steps.bundle.outputs.file-name }}

      - uses: actions/cache/save@v4
        if: !inputs.publish-mode && inputs.save-cache && steps.restore-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}
