name: Flatpak (Experimental)

on:
  push:
    paths-ignore: ['**.md']
    branches: [master]
  pull_request:
    paths-ignore: ['**.md']
    branches: [master]

jobs:
  flatpak_builder:
    name: Bundle
    runs-on: [ubuntu-latest]
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
    - name: 'Check for Github Labels'
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        LABELS_URL="$(echo ${{ github.event.pull_request.url }} | sed s'/pulls/issues/')"
        LABEL_FOUND="$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${LABELS_URL}/labels" | sed -n 's/.*"name": "\(.*\)",/\1/p' | grep 'Seeking Testers' || true)"
        if [ "${LABEL_FOUND}" = "Seeking Testers" ]; then
          echo "SEEKING_TESTERS=1" >> $GITHUB_ENV
        else
          echo "SEEKING_TESTERS=0" >> $GITHUB_ENV
        fi

    - name: Checkout
      uses: actions/checkout@v2.3.3
      if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
      with:
        submodules: 'recursive'

    - name: Install packages
      if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
      run: |
        PACKAGES="jq"
        [ "${{ matrix.arch }}" != "x86_64" ] && PACKAGES="$PACKAGES docker"
        dnf install -y $PACKAGES

    - name: Get Flatpak Manifest Deps Hash
      if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
      shell: bash
      run: |
        FLATPAK_DEPS_HASH=`cat CI/flatpak/com.obsproject.Studio.json | jq '. | {runtime, "runtime-version", sdk, modules} | del(.modules[] | select(.name == "obs"))' | sha256sum | cut -f1 -d' '`
        echo "FLATPAK_DEPS_HASH=$FLATPAK_DEPS_HASH" >> $GITHUB_ENV

    - name: Set up QEMU
      if: success() && matrix.arch != 'x86_64' && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Build Flatpak Manifest
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      if: success() && (github.event_name != 'pull_request' || env.SEEKING_TESTERS == '1')
      with:
        bundle: obs-studio-${{ github.sha }}.flatpak
        manifest-path: CI/flatpak/com.obsproject.Studio.json
        cache-key: flatpak-builder-${{ env.FLATPAK_DEPS_HASH }}
        arch: ${{ matrix.arch }}
